name: Test Commit

on:
  push:
    branches: [master, develop]
  pull_request:

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'
      - name: Install dependencies
        run: |
          yarn install
          cd examples
          yarn install
          cd ..
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn test
        env:
          CI: true
      - name: Typings test
        run: yarn test:type
      - name: Build
        run: yarn build
        env:
          NODE_ENV: production
      - name: Codecov
        run: npx codecov -f coverage/*.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
